### PR TITLE
fixed parent pom. it compiled java dir. had to be kotlin dir

### PR DESCRIPTION
**Pull request by miguelius**
Hi, I'm starting a project with tornadofx. I've found a small issue with the parent pom and also added a couple of README.md

Cheers,
Miguel

### CODE REVIEW

**Comment by edvin** [comment]
Hi! The sources _are_ in src/main/java, so changing the pom to point them to src/main/kotlin would fail the builds :)

This samples project isn't maintained at the moment, and it might not be the best source of information. We should really reboot this initiative.

**Comment by miguelius** [comment]
totally right! Just the item view model was in kotlin dir. Sorry! I'd like to use tornado i a jnlp app. Which would be the best source of information?

**Comment by edvin** [comment]
There is nothing TornadoFX specific to think about really, just do as you would do with any other JavaFX app :) You could also look into FXLauncher as an alternative.

**Comment by miguelius** [comment]
Great! I'll take FXLauncher in account. If I change all the directories to kotlin, would you accept the pull request? I'm also working on a Workspace example!

**Comment by edvin** [comment]
Sure :) Thanks!

**Pull request closed without merging**
