### PR TITLE
update version numbers for tornadofx and kotlin

### PR DESCRIPTION
**Pull request by jschneider**

### CODE REVIEW

**Comment by edvin** [comment]
Kotlin 1.2 should be good by now :)

**Comment by jschneider** [comment]
It is the same version number as of tornadofx 1.7.12.
I didn't want to get conflicting Kotlin versions within the dependencies.

**Comment by edvin** [comment]
Good point :)

**Comment by jschneider** [comment]
Uuhm. I changed the Kotlin version to 1.2. Did you realize that?

**Comment by edvin** [comment]
No, but it doesn't matter - it's completely compatible, and the build system should avoid duplicates. In any case, I'll release 1.7.13 shortly, so we can do another update ASAP :)

**Pull request merged**
